### ISSUE TITLE
What went wrong?

### ISSUE THREAD

**Issue by ron3dhj** [cromachina/fanbox-bot#2]
![gambar](https://user-images.githubusercontent.com/109651844/179922950-e884244d-a3b2-40d2-b7ba-314352fd98fd.png)

Hello @cromachina, thank you so much for creating this code!, I tried your code and of course I already modifying it to make sure I follow the instruction what it's needed to be modify but I dunno if this already work or not, I'm new to a programming stuff but it seems there's no slot for Discord Server ID, and how to make the BOT online ? is it using uptimerobot to make it online ? I hope I can get a reply soon, Thank you

EDIT: It seems i forgot to turn this on
![gambar](https://user-images.githubusercontent.com/109651844/179966745-771e38b3-d27f-473f-a718-4f105af88c9e.png)

**Comment by cromachina** [comment]
Privileged Gateway Intents seems to be missing from the Discord setup docs. I will mention this in the readme. Thanks!
