### ISSUE TITLE
Bot connects, but nothing happens

### ISSUE THREAD

**Issue by Pimmela1** [cromachina/fanbox-bot#4]
Hello, I'm currently stuck at this part:

![github](https://user-images.githubusercontent.com/120783799/208239379-c0112de8-9a3a-40c8-85a4-995745a3b54b.JPG)

It says "Fanbox Bot#6234 has connected to Discord!", but nothing happens after that :/
No role changes or anything.
Any tips?

**Comment by cromachina** [comment]
Your bot needs appropriate permissions to grant roles, and must be invited to the server with those roles configured in the bot invite. The same permissions need to be configured in the server as well.

After it has the permissions it needs, you can message a user's ID to receive your configured role. If nobody messages the bot, nothing happens.

**Comment by Pimmela1** [comment]
Ahh okay, I just forgot to message the user's pixiv ID to the bot. Seems to work now! Thank you! :)

However, I did encounter another problem.
If the user unsubscribes, their role doesn't seem to update automatically. It only updates if the user messages the bot again.
Do I need to adjust the cleanup routine for the roles to update?

**Comment by cromachina** [comment]
> If the user unsubscribes, their role doesn't seem to update automatically. It only updates if the user messages the bot again.
Do I need to adjust the cleanup routine for the roles to update?

I've not implemented this feature because I've not had a need for it myself. The cleanup routine right now only will remove people who have never successfully acquired a role.

**Comment by cromachina** [comment]
To implement this feature, the whole user list should be retrieved from fanbox/fantia, and then it should be checked against the registry object on some periodic interval, say like every 24 hours.

**Comment by Pimmela1** [comment]
> To implement this feature, the whole user list should be retrieved from fanbox/fantia, and then it should be checked against the registry object on some periodic interval, say like every 24 hours.

Oh okay. I just started learning all of this stuff, so it would be impossible for me to set that up😅. Thank you very much anyways! <3

**Comment by cromachina** [comment]
@Pimmela1 automatic derole has been implemented.
