### ISSUE TITLE
Help me solve the unknown role error.

### ISSUE THREAD

**Issue by camapchienxu123** [cromachina/fanbox-bot#5]
Thank you for your patience, sorry for commenting on unrealated commit because I'm a github noob. I let my yml look like this:
plan_roles:
  '348830': 1116399299308294246

# Allow an unsubscribed user to get access if they have subscribed before.
allow_fallback: False
# This must be a number, same as above.
fallback_role: 1116399299308294246

But I still have the same error like before, the bot regconized the subcriber but it have some issue with the role.

discord.errors.NotFound: 404 Not Found (error code: 10011): Unknown Role
[2023-06-08 23:31:55,100][INFO] User: Pipisvoir#9893; Message: "!8591772"; Response: system_error

**Comment by cromachina** [comment]
Does the bot have appropriate permissions in your server?

**Comment by camapchienxu123** [comment]
yeah I gave it administrator permission

**Comment by cromachina** [comment]
Okay, and to make sure, the way you got the role ID is `Server settings -> Roles -> right click on role -> Copy Role ID`, right?

**Comment by camapchienxu123** [comment]
right

**Comment by camapchienxu123** [comment]
I tested in another server and another role, bot gave me this error

discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
[2023-06-08 23:48:12,197][INFO] User: Pipisvoir#9893; Message: "!8591772"; Response: system_error

**Comment by cromachina** [comment]
FYI the bot can only work with a single server per running instance, so if you invite it to multiple servers, it will only work for the first server it is a member of.

**Comment by camapchienxu123** [comment]
alright, after it just stay in 1 server, it gave me this error in test:

discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
[2023-06-08 23:58:52,825][INFO] User: Pipisvoir#9893; Message: "!8591772"; Response: system_error

**Comment by cromachina** [comment]
Okay, now you need to fix permissions. Whatever server it's in, it does not have appropriate permissions. If the bot's role has full permissions, it also needs to be invited to the server with the correct OAuth permissions from the bot dev webpage. You can simply re-invite the bot with the updated permissions.

**Comment by camapchienxu123** [comment]
I just need to tick administrator or right things?

**Comment by cromachina** [comment]
Administrator would be the easiest thing to pick.

**Comment by camapchienxu123** [comment]
Oh it works, so if I want to give a role for my member, how should I do it? I just know !<pixiv_id> and !purge,reset.

**Comment by camapchienxu123** [comment]
When I !<pixiv_id> it gave my own account the role

**Comment by cromachina** [comment]
You don't need to put `!` in front of the Pixiv ID. The member themselves sends their own pixiv ID and gets the role. It's meant to be automated so that you don't have to do this yourself.

**Comment by camapchienxu123** [comment]
It worked, thank you a lot friend.

**Comment by cromachina** [comment]
No problem. I will update documentation to make this all more clear.

**Comment by cromachina** [comment]
https://github.com/cromachina/fanbox-bot/commit/d0a73b32f503268d67cc0a02627ad5f491a5a153 Updated documentation based on this conversation.
