### ISSUE TITLE
Feature request: "Add user" admin command

### ISSUE THREAD

**Issue by bell20xx** [cromachina/fanbox-bot#6]
First of all, thank you cromachina for this repo, it works great.

Some users don't seem to understand how this whole verification process works and end up messaging me anyway or just message the bot wrongly, and since you are adding Admin commands it would be cool if there was a command to add a user manually, something like **!add-user <PIXIV_ID> <DISCORD_ID>** (just an idea of course).

**Comment by cromachina** [comment]
1b28831d2005c59a2c71bdf404e322ff3c9d4b70 now has an `add-user` command as specified. Please pull latest to try it out.

**Comment by bell20xx** [comment]
Very good, thanks!
