### ISSUE TITLE
Value Error: Invalid literal for int with base 10 role_id

### ISSUE THREAD

**Issue by jepminer** [cromachina/fanbox-bot#7]
running python3 main.py is giving this error, it deletes itself from the terminal and then pops back up over and over in a loop, from what I understand this means that the roleid should just be numbers but it is, it's  
'FanboxPlanId': RoleId 
formatted exactly like that spaces and all using the exact same format as the placeholder in the config file

**Comment by cromachina** [comment]
Have you resolved it? Formatting error? UTF-8 error?

**Comment by jepminer** [comment]
I did solve it, didn't realise the fallback role id would also need filling out even if the feature was disabled, I do have a different error now though which is:
Permission error: [errno 13] permission denied (file location)/log.txt
but it doesn't seem to have made a log.txt so can't even use that for clues.

more context: I'm running on raspberry pi os

**Comment by cromachina** [comment]
You probably need to run `chmod a+w .` to grant write permissions in the folder you are running the bot out of. It will need this also to create the user database file.
