### ISSUE TITLE
Bot can give out more than one role per pixiv account

### ISSUE THREAD

**Issue by jepminer** [cromachina/fanbox-bot#8]
so got the bot working that's all fine and good however in testing we found that anyone can use the pixiv profile of anyone else in the server to gain a role, even if the actual owner already has a role. as the bot makes a database it's probably an easy fix to only allow one role per user id but I don't actually know, not good at programming.

**Comment by cromachina** [comment]
I can add a config option and some code to allow you to make access more strict, but it will be in a day or so because I'm working on other stuff.

I found that this kind of access does not happen much in practice, particularly if you mention that you periodically read the access logs.

**Comment by jepminer** [comment]
that'd be great thanks as it'll just be running on a headless pi zero so the logs probably won't be ever read.

**Comment by cromachina** [comment]
84dbe28dd71ea911dbdb6760ba397f4976dbfab4 now implements this with some new admin commands too. You will have to merge your config template again because I had to add new config options.
